### PR TITLE
move header decorate in the request getHeader method

### PR DESCRIPTION
**Pull request by jiqimaogou**
request getHeader method is called in the network thread(not in the main
thread), sometime we need to get token from accountmanager, the
accountmanager gettoken method is blocking.

### CODE REVIEW

**Comment by orhanobut** [comment]
WaspRequest is actually created in the caller thread with the same as builder. (usually it is main thread). After request object is created, then we add it to the queue and the request is done in the background thread. This wouldn't do any affect. Did it solve your problem?

**Comment by jiqimaogou** [comment]
```
  RequestInterceptor interceptor = new SimpleInterceptor() {
      @Override
      public AuthToken getAuthToken() {
          return new AuthToken(token, true);
      }                                                     
  }
```
sometimes we get the token from the AccountManager, which is not allowed in the main thread.

**Comment by orhanobut** [comment]
I think we can solve the problem in another way, this pr won't solve the main issue. let's create an issue for this? what do you think?

**Comment by orhanobut** [comment]
closing the PR.

**Pull request closed without merging**
